version: '3.4'
services:
  docker-service-webhook:
    build: .
    image: mities/docker-service-webhook-endpoint
    restart: always
    ports:
      - 8888:80
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
